# Simulation Code T = 1

## Import libraries

In [1]:
from utils.dynamicRieszFunctions import estimateDynamicRiesz
from utils.dynamicRieszFunctions import estimateDynamicRiesz_all
from utils.dynamicRieszBradic import estimateBradicT1
import torch
import pandas as pd
import time
import numpy as np
from torch.distributions import Normal

/Users/wisserutgers/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

## Estimation Settings

In [2]:
lasso_cv_settings = {
    'b_degree' : 1,
    'cv_folds' : 5,
    'random_state' : 42
}

lasso_a_settings = {
    'lambda_val' : 0,
    'beta_start' : None,
    'D_LB' : 0,
    'D_add' : 0.2,
    'c1' : 0.1, # CHANGED FROM "CV"
    'c2' : 0.1,
    'tol' : 1e-5,
    'max_iter' : 100,
    'b_degree' : 1,
    'control' : {'maxIter': 1000, 'optTol': 1e-5, 'zeroThreshold': 1e-6}
}

lasso_f_settings = {
    'lambda_val' : 0,
    'beta_start' : None,
    'D_LB' : 0,
    'D_add' : 0.2,
    'c1' : 0.1, # CHANGED FROM "CV"
    'c2' : 0.1,
    'tol' : 1e-5,
    'max_iter' : 100,
    'b_degree' : 1,
    'control' : {'maxIter': 1000, 'optTol': 1e-5, 'zeroThreshold': 1e-6}
}

rf_a_settings = {
    'l2' : 0,
    'n_estimators' : 100,
    'criterion' : "mse",
    'max_depth' : None,
    'min_samples_split' : 10,
    'min_samples_leaf' : 5,
    'min_weight_fraction_leaf' : 0.,
    'min_var_fraction_leaf' : None,
    'min_var_leaf_on_val' : False,
    'max_features' : "auto",
    'min_impurity_decrease' : 0.,
    'max_samples' : .45,
    'min_balancedness_tol' : .45,
    'honest' : True,
    'inference' : True,
    'fit_intercept' : True,
    'subforest_size' : 4,
    'n_jobs' : -1,
    'random_state' : None,
    'verbose' : 0,
    'warm_start' : False
}

rf_f_settings = {
    'l2' : 0,
    'n_estimators' : 100,
    'criterion' : "mse",
    'max_depth' : None,
    'min_samples_split' : 10,
    'min_samples_leaf' : 5,
    'min_weight_fraction_leaf' : 0.,
    'min_var_fraction_leaf' : None,
    'min_var_leaf_on_val' : False,
    'max_features' : "auto",
    'min_impurity_decrease' : 0.,
    'max_samples' : .45,
    'min_balancedness_tol' : .45,
    'honest' : True,
    'inference' : True,
    'fit_intercept' : True,
    'subforest_size' : 4,
    'n_jobs' : -1,
    'random_state' : None,
    'verbose' : 0,
    'warm_start' : False
}

net_a_settings = {
    'test_split' : 0,
    'learner_lr' : 1e-4,
    'learner_l2' : 1e-3,
    'learner_l1' : 0,
    'n_epochs' : 100,
    'earlystop_rounds' : 20,
    'earlystop_delta' : 1e-3,
    'bs' : 64,
    'optimizer' : 'adam',
    'warm_start' : False,
    'logger' : None,
    'model_dir' : '.',
    'device' : torch.cuda.current_device() if torch.cuda.is_available() else None,
    'n_hidden' : 100,
    'drop_prob' : 0,
    'degree' : 2,
    'interaction_only' : True,
    'n_common' : 200,
    'act_func' : 'elu'
}

net_f_settings = {
    'test_split' : 0,
    'learner_lr' : 1e-4,
    'learner_l2' : 1e-3,
    'learner_l1' : 0,
    'n_epochs' : 100,
    'earlystop_rounds' : 20,
    'earlystop_delta' : 1e-3,
    'bs' : 64,
    'optimizer' : 'adam',
    'warm_start' : False,
    'logger' : None,
    'model_dir' : '.',
    'device' : torch.cuda.current_device() if torch.cuda.is_available() else None,
    'n_hidden' : 100,
    'drop_prob' : 0,
    'degree' : 2,
    'interaction_only' : True,
    'n_common' : 200,
    'act_func' : 'elu'
}

## Generate data

#### Simulation settings:

In [3]:
torch.manual_seed(123);

# Parameters
N = 5000
tmax = 20

# Higher dimensions = more sparsity. Minimum is dimX1 = dimX2 = 3
p1 = 1

#### Define treatment probability function

In [4]:
# Bounds (only for truncated distributions)
lower = 0.10
upper = 0.90

# Define logistic function
def logistic(x):
    return torch.exp(x) / (1 + torch.exp(x))

# Define a truncated logistic function
def truncated_logistic(x):
    return lower + (upper - lower) * logistic(x)

# Define func_link function (nonlinear probability function from Bradic)
def func_link(x):
    return (x > 0) * torch.abs(x) / (torch.abs(x) + 1) + (x < 0) / (torch.abs(x) + 1)

# Define a truncated func_link function
def truncated_link(x):
    return lower + (upper - lower) * func_link(x)

# Simple nonlinear probability (from adversarial Riesz paper)
def truncated_adv(x):
    return lower + (upper - lower) * (x > 0)

# Simple nonlinear probability (from adversarial Riesz paper)
def double_nonlinear(x):
    return lower + (upper - lower) * (x > - 1/2) * (x < 1/2)

# Simple nonlinear probability (from adversarial Riesz paper)
def nonsymmetric(x):
    return lower + 0.5 * (upper - lower) * (x < - 1/4) + (upper - lower) * (x > 1/4) 

normal_dist = Normal(0, 1)
def probit(x):
    return lower + (upper - lower) * normal_dist.cdf(x)

In [5]:
treatment_probability_func = truncated_adv

#### Generate data

In [6]:
# Coefficients
# beta_pi1_0 = 0
# beta_pi1_S1 = torch.tensor([1, 1,0,0,0,0], dtype=torch.float32).reshape(-1,1) 
# beta_g0_0 = 1 * 4
# beta_g0_S1 = torch.tensor([1, 0,0,0,0,0], dtype=torch.float32).reshape(-1,1) * 2
# beta_g1_0 = -1 * 5
# beta_g1_S1 = torch.tensor([-1, 0,0,0,0,0], dtype=torch.float32).reshape(-1,1) * 1

# # 1 covariate
# beta_pi1_S1 = torch.tensor([1], dtype=torch.float32).reshape(-1,1) 
# beta_g0_0 = 2 * 1
# beta_g0_S1 = torch.tensor([-1], dtype=torch.float32).reshape(-1,1) * 6
# beta_g1_0 = -1 * 3
# beta_g1_S1 = torch.tensor([1], dtype=torch.float32).reshape(-1,1) * 9

# Adversarial Riesz paper
beta_pi1_0 = 0
beta_pi1_S1 = torch.tensor([1], dtype=torch.float32).reshape(-1,1) 
beta_g0_0 = 0
beta_g0_S1 = torch.tensor([1.2], dtype=torch.float32).reshape(-1,1) 
beta_g1_0 = 2.2
beta_g1_S1 = torch.tensor([1], dtype=torch.float32).reshape(-1,1) 

# Set seed
torch.manual_seed(123)

# Generate data
S1_all = torch.randn(N * tmax, p1)
pi1_all = treatment_probability_func(beta_pi1_0 + S1_all @ beta_pi1_S1).reshape(-1,1)
A1_all = torch.bernoulli(pi1_all).int().reshape(-1,1)

# g_all = ((A1_all == 0).float() * (beta_g0_0 + S1_all @ beta_g0_S1 ) + 
#          (A1_all == 1).float() * (beta_g1_0 + S1_all @ beta_g1_S1 ))
# g_all = ((A1_all == 0).float() * (beta_g0_0 + (S1_all @ beta_g0_S1 > 0) * 3 ) + 
#          (A1_all == 1).float() * (beta_g1_0 + (S1_all @ beta_g1_S1> 0) * 2 ))
g_all = ((A1_all == 0).float() * (beta_g0_0 + (S1_all > 0) * beta_g0_S1 ) + 
         (A1_all == 1).float() * (beta_g1_0 + (S1_all > 0) * beta_g0_S1 + S1_all ))
zeta_all = torch.randn(N * tmax,1)
Y_all = g_all + zeta_all

#### True values:

In [7]:
# mu1_1_all = beta_g1_0 + (S1_all @ beta_g0_S1 > 0) * 3
# mu1_0_all = beta_g0_0 + (S1_all @ beta_g1_S1 > 0) * 2

# theta0 = beta_g0_0 + 0.5 * 3
# theta1 = beta_g1_0 + 0.5 * 2

# mu1_1_all = beta_g1_0 + S1_all @ beta_g1_S1
# mu1_0_all = beta_g0_0 + S1_all @ beta_g0_S1

# theta0 = beta_g0_0 
# theta1 = beta_g1_0 

mu1_1_all = beta_g1_0 + S1_all + (S1_all > 0) * beta_g0_S1
mu1_0_all = beta_g0_0 + (S1_all > 0) * beta_g0_S1

theta0 = beta_g0_0 + 0.5 * 1.2
theta1 = beta_g1_0 + 0.5 * 1.2 

theta = theta1 - theta0
print(theta, theta1, theta0)

2.2 2.8000000000000003 0.6

## Estimation:

#### Estimation settings

In [8]:
folds = 2

time0 = time.time()

#### Estimation

In [9]:
pred_theta = torch.zeros(tmax,5)
pred_sig = torch.zeros(tmax,5)

RR1 = torch.zeros(N,tmax,5)
RR2 = torch.zeros(N,tmax,5)
f1 = torch.zeros(N,tmax,5)
f2 = torch.zeros(N,tmax,5)

for t in range(0,tmax):

    # Get data for current iteration
    S1 = S1_all[(t) * N : (t+1) * N, :]
    A1 = A1_all[(t) * N : (t+1) * N]
    Y = Y_all[(t) * N : (t+1) * N]

    X = ((S1))
    X_index = torch.tensor([S1.shape[1]-1])
    D = ((A1))

    # Set counterfactual of interest
    d = 1 * torch.ones(D.shape) 

    #---------------------------------------------------------------------------
    # Estimator 1: Oracle
    pi1 = pi1_all[(t) * N : (t+1) * N]
    mu1_1 = mu1_1_all[(t) * N : (t+1) * N]
    mu1_0 = mu1_0_all[(t) * N : (t+1) * N]
    if d[0] == 1:
        gamma = A1 / pi1  
        theta_hat = (gamma * Y - (gamma - 1) * mu1_1)
        pred_theta[t,0] = torch.mean( theta_hat )
        pred_sig[t,0] = torch.sqrt(torch.mean((theta_hat - torch.mean(theta_hat) ) ** 2))
        f2[:,t,:1] = mu1_1
    else:
        gamma = (1 - A1) / (1 - pi1  )
        theta_hat = (gamma * Y - (gamma - 1) * mu1_0  )
        pred_theta[t,0] = torch.mean( theta_hat )
        pred_sig[t,0] = torch.sqrt(torch.mean((theta_hat - torch.mean(theta_hat) ) ** 2))
        f2[:,t,:1] = mu1_0

    RR2[:,t,:1] = gamma

    #---------------------------------------------------------------------------
    # Estimator 2: Bradic
    bradic_result = estimateBradicT1(Y,S1,A1, folds)
    if d[0] == 1:
        pred_theta[t,1] = bradic_result[1]
        pred_sig[t,1] = bradic_result[3]
        RR2[:,t,1:2] = bradic_result[5]
        f2[:,t,1:2] = bradic_result[7]
    elif d[0] == 0:
        pred_theta[t,1] = bradic_result[2]
        pred_sig[t,1] = bradic_result[4]
        RR2[:,t,1:2] = bradic_result[6]
        f2[:,t,1:2] = bradic_result[8]

    coeff = bradic_result[7]
    #---------------------------------------------------------------------------
    # Estimator 3: LASSO 

    # pred_theta[t,2], pred_sig[t,2], RR1[:,t,2:3], RR2[:,t,2:3], f1[:,t,2:3], f2[:,t,2:3] = estimateDynamicRiesz(Y, X, D, d, X_index, folds,
    #                                                                  method_a = "LASSO", lasso_a_settings = lasso_a_settings,
    #                                                                     method_f = "LASSO", lasso_f_settings = lasso_f_settings)

    # #---------------------------------------------------------------------------
    # # Estimator 4: RF 

    # pred_theta[t,3], pred_sig[t,3], RR1[:,t,3:4], RR2[:,t,3:4], f1[:,t,3:4], f2[:,t,3:4] = estimateDynamicRiesz(Y, X, D, d, X_index, folds,
    #                                                                  method_a = "RF", rf_a_settings = rf_a_settings,
    #                                                                     method_f = "RF", rf_f_settings = rf_f_settings)

    # # # #---------------------------------------------------------------------------
    # # # # Estimator 5: Net 

    # pred_theta[t,4], pred_sig[t,4], RR1[:,t,4:5], RR2[:,t,4:5],  f1[:,t,4:5], f2[:,t,4:5] = estimateDynamicRiesz(Y, X, D, d, X_index, folds,
    #                                                                  method_a = "Net", net_a_settings = net_a_settings,
    #                                                                     method_f = "Net", net_f_settings = net_f_settings)

    pred_theta[t,2:], pred_sig[t,2:], RR1[:,t,2:], RR2[:,t,2:], f1[:,t,2:], f2[:,t,2:] = estimateDynamicRiesz_all(Y, X, D, d, X_index, folds)

    if t % 10 == 0:
        print("Time until iteration ",t, ": ", time.time() - time0)

print("Finished. Total time: ", time.time() - time0)

tensor([[0.2539],
        [0.2536],
        [2.8317],
        [1.0163]])
tensor([[0.3175],
        [0.3192],
        [2.8273],
        [0.9538]])
Time until iteration  0 :  3.4968440532684326
tensor([[0.3052],
        [0.2851],
        [2.8250],
        [0.9765]])
tensor([[0.3452],
        [0.2934],
        [2.6503],
        [1.1000]])
tensor([[0.3481],
        [0.3386],
        [2.7770],
        [0.9489]])
tensor([[0.3525],
        [0.3062],
        [2.7200],
        [1.0061]])
tensor([[0.2853],
        [0.3159],
        [2.8017],
        [0.9888]])
tensor([[0.3622],
        [0.3412],
        [2.7403],
        [0.9912]])
tensor([[0.3143],
        [0.2793],
        [2.7919],
        [1.0119]])
tensor([[0.3141],
        [0.2777],
        [2.7365],
        [0.9904]])
tensor([[0.3561],
        [0.3256],
        [2.6710],
        [0.9721]])
tensor([[0.4003],
        [0.3619],
        [2.6905],
        [0.9140]])
tensor([[0.3481],
        [0.3017],
        [2.7370],
        [0.9541]])
tensor([[0.3339],
        [0.2779],
        [2.7561],
        [1.0118]])
tensor([[0.3092],
        [0.2617],
        [2.7851],
        [0.9955]])
tensor([[0.3393],
        [0.2684],
        [2.7334],
        [1.0223]])
tensor([[0.4015],
        [0.2888],
        [2.6498],
        [1.0189]])
tensor([[0.3701],
        [0.3425],
        [2.7676],
        [0.9075]])
tensor([[0.3602],
        [0.3123],
        [2.6525],
        [1.0000]])
tensor([[0.4001],
        [0.3659],
        [2.6964],
        [0.9417]])
tensor([[0.2804],
        [0.2525],
        [2.8805],
        [0.9392]])
tensor([[0.2796],
        [0.3101],
        [2.7656],
        [0.9918]])
Time until iteration  10 :  37.332701206207275
tensor([[0.3300],
        [0.2862],
        [2.7227],
        [1.0598]])
tensor([[0.3176],
        [0.2747],
        [2.8048],
        [0.9976]])
tensor([[0.3173],
        [0.3263],
        [2.7779],
        [0.9037]])
tensor([[0.3357],
        [0.3001],
        [2.7552],
        [1.0206]])
tensor([[0.2807],
        [0.2871],
        [2.7782],
        [1.0527]])
tensor([[0.3447],
        [0.3026],
        [2.7488],
        [1.0051]])
tensor([[0.2896],
        [0.3234],
        [2.8165],
        [1.0091]])
tensor([[0.3153],
        [0.2870],
        [2.7584],
        [1.0684]])
tensor([[0.3349],
        [0.2969],
        [2.7306],
        [0.9851]])
tensor([[0.3249],
        [0.2841],
        [2.7622],
        [0.9911]])
tensor([[0.3143],
        [0.2278],
        [2.7616],
        [1.0255]])
tensor([[0.3153],
        [0.2762],
        [2.7148],
        [1.0431]])
tensor([[0.2987],
        [0.2419],
        [2.8129],
        [0.9949]])
tensor([[0.3760],
        [0.3157],
        [2.7229],
        [0.9660]])
tensor([[0.3182],
        [0.3216],
        [2.7888],
        [0.9693]])
tensor([[0.2778],
        [0.2890],
        [2.8428],
        [1.0079]])
tensor([[0.2887],
        [0.3249],
        [2.8075],
        [0.9555]])
tensor([[0.3090],
        [0.3414],
        [2.8353],
        [0.9704]])
Finished. Total time:  67.48824334144592

## Compute statistics

#### Get true value

In [10]:
true_value = theta1

#### Compute statistics

In [11]:
bias = torch.mean(pred_theta[:t+1,:] - true_value, 0)
rmse = torch.sqrt(torch.mean( (pred_theta[:t+1,:] - true_value) ** 2, 0))

ub = pred_theta[:t+1,:] + 1.96 * pred_sig[:t+1,:] / torch.sqrt(torch.tensor(N))
lb = pred_theta[:t+1,:] - 1.96 * pred_sig[:t+1,:] / torch.sqrt(torch.tensor(N))

coverage = torch.mean( ( (true_value >= lb) & (true_value <= ub) ).float() , 0 )
interval_length = torch.mean(ub - lb,0)

# Create a DataFrame
data = {
    "Method": ["Oracle", "Bradic", "LASSO", "RF", "Net"],
    "Bias": bias.ravel(),
    "RMSE": rmse.ravel(),
    "Coverage": coverage.ravel(),
    "Interval Length": interval_length.ravel()
}

#### Print results

In [12]:
df = pd.DataFrame(data)
print(df)

   Method      Bias      RMSE  Coverage  Interval Length
0  Oracle -0.007654  0.036877      0.95         0.156062
1  Bradic  0.267390  0.722790      0.95         2.205797
2   LASSO  0.282319  0.283708      0.00         0.136941
3      RF -0.022785  0.047870      0.95         0.185130
4     Net -2.800000  2.800000      0.00         0.000000

In [13]:
pred_theta

tensor([[2.8347, 2.9324, 3.1136, 2.8004, 0.0000],
        [2.7639, 2.3938, 3.0556, 2.7492, 0.0000],
        [2.8009, 2.7336, 3.1174, 2.8116, 0.0000],
        [2.7985, 2.1584, 3.1006, 2.8008, 0.0000],
        [2.7395, 3.0758, 3.0472, 2.7187, 0.0000],
        [2.7832, 5.4950, 3.0488, 2.7516, 0.0000],
        [2.8244, 2.8450, 3.0887, 2.8084, 0.0000],
        [2.7590, 3.8717, 3.0699, 2.7250, 0.0000],
        [2.7772, 3.5758, 3.1059, 2.7534, 0.0000],
        [2.8123, 3.0330, 3.0930, 2.7807, 0.0000],
        [2.8263, 3.1281, 3.0818, 2.8166, 0.0000],
        [2.7973, 2.6220, 3.1039, 2.7703, 0.0000],
        [2.7903, 2.6855, 3.1186, 2.7887, 0.0000],
        [2.7538, 3.4444, 3.0373, 2.7504, 0.0000],
        [2.7771, 2.9809, 3.0700, 2.7822, 0.0000],
        [2.7880, 2.8311, 3.0606, 2.7764, 0.0000],
        [2.7204, 2.6601, 3.0406, 2.6787, 0.0000],
        [2.7840, 2.9655, 3.0782, 2.7836, 0.0000],
        [2.8793, 2.9026, 3.1373, 2.8766, 0.0000],
        [2.8367, 3.0131, 3.0774, 2.8210, 0.0000]])

In [14]:
check_t = 0
# Compare RR:
pd.DataFrame(RR2[:,check_t,:].numpy().squeeze()).head(50)

            0          1         2          3    4
0    1.111111   1.450398  2.477577   1.161804  0.0
1    0.000000   0.000000  0.033516   0.000000  0.0
2    0.000000   0.000000  0.033516   0.000000  0.0
3    0.000000   0.000000  0.033516   0.000000  0.0
4    1.111111   1.440606  2.422950   1.150487  0.0
5    1.111111   1.224803  1.833463   1.146133  0.0
6   10.000000   2.523682  3.528239  13.963461  0.0
7    0.000000   0.000000  0.004227   0.000000  0.0
8    1.111111   1.175889  1.666981   1.086500  0.0
9    0.000000   0.000000  0.033516   0.000000  0.0
10   1.111111   1.207094  1.761585   1.053866  0.0
11   0.000000   0.000000  0.033516   0.000000  0.0
12   1.111111   1.636396  2.775589   1.109789  0.0
13   1.111111   1.015638 -0.501538   1.156064  0.0
14   1.111111   1.318702  2.179404   1.128539  0.0
15   1.111111   1.522989  2.573107   1.135379  0.0
16   0.000000   0.000000  0.033516   0.000000  0.0
17  10.000000   9.787966  5.038822  11.110106  0.0
18   0.000000   0.000000  0.033516   0.000000  0.0
19   1.111111   1.126496  1.382801   1.240404  0.0
20   1.111111   1.030813  0.092569   1.170998  0.0
21   1.111111   1.056384  0.621911   1.146320  0.0
22   1.111111   1.057853  0.708394   1.109423  0.0
23   0.000000   0.000000  0.004227   0.000000  0.0
24   1.111111   1.320205  2.143338   1.020938  0.0
25  10.000000  30.394630  6.079722  11.506110  0.0
26   1.111111   1.113683  1.290739   1.103932  0.0
27   0.000000   0.000000  0.033516   0.000000  0.0
28  10.000000  12.409908  5.273558  10.186276  0.0
29   0.000000   0.000000  0.004227   0.000000  0.0
30   0.000000   0.000000  0.004227   0.000000  0.0
31   0.000000   0.000000  0.004227   0.000000  0.0
32   0.000000   0.000000  0.004227   0.000000  0.0
33   1.111111   1.637722  2.777383   1.109407  0.0
34   0.000000   0.000000  0.033516   0.000000  0.0
35   1.111111   1.096448  1.092165   1.154003  0.0
36   0.000000   0.000000  0.033516   0.000000  0.0
37   0.000000   0.000000  0.033516   0.000000  0.0
38   0.000000   0.000000  0.033516   0.000000  0.0
39   0.000000   0.000000  0.033516   0.000000  0.0
40   1.111111   1.139755  1.417062   1.106803  0.0
41   1.111111   1.032648  0.143268   1.167044  0.0
42   1.111111   1.241780  1.897236   1.147174  0.0
43   0.000000   0.000000  0.004227   0.000000  0.0
44   1.111111   1.759957  2.928556   1.064805  0.0
45   0.000000   0.000000  0.004227   0.000000  0.0
46   1.111111   1.526369  2.578749   1.132807  0.0
47   0.000000   0.000000  0.004227   0.000000  0.0
48   1.111111   1.138346  1.460001   1.272913  0.0
49   1.111111   1.028192  0.014709   1.175094  0.0

In [15]:
pd.DataFrame(f2[:,check_t,:].numpy().squeeze()).head(50)

           0         1         2         3    4
0   3.737370  3.517396  3.514087  3.514087  0.0
1   2.022223  2.920760  2.918522  2.918522  0.0
2   1.896472  2.760625  2.758443  2.758443  0.0
3   1.611988  2.398353  2.396296  2.396296  0.0
4   3.748605  3.591073  3.588605  3.588605  0.0
5   4.060341  3.988047  3.985443  3.985443  0.0
6   1.980362  2.811453  2.806756  2.806756  0.0
7   1.820830  2.609264  2.604169  2.604169  0.0
8   4.167107  4.062038  4.059800  4.059800  0.0
9   1.007498  1.628576  1.626783  1.626783  0.0
10  4.098352  4.036452  4.033831  4.033831  0.0
11  0.790277  1.351959  1.350262  1.350262  0.0
12  3.579380  3.317161  3.313458  3.313458  0.0
13  5.295148  5.560492  5.557346  5.557346  0.0
14  3.895447  3.717739  3.714825  3.714825  0.0
15  3.669199  3.489954  3.487520  3.487520  0.0
16  2.122980  3.049067  3.046786  3.046786  0.0
17  1.179528  1.796488  1.789794  1.789794  0.0
18  2.031044  2.931993  2.929751  2.929751  0.0
19  4.317764  4.252979  4.251117  4.251117  0.0
20  4.980969  5.160407  5.157399  5.157399  0.0
21  4.701040  4.803935  4.801050  4.801050  0.0
22  4.675302  4.706116  4.705145  4.705145  0.0
23  1.999047  2.835133  2.830483  2.830483  0.0
24  3.896471  3.779370  3.776837  3.776837  0.0
25  0.627696  1.097104  1.089035  1.089035  0.0
26  4.366571  4.314836  4.313096  4.313096  0.0
27  1.051856  1.685062  1.683250  1.683250  0.0
28  1.041132  1.671407  1.669599  1.669599  0.0
29  3.725471  3.502315  3.498977  3.498977  0.0
30  1.568495  2.289458  2.283734  2.283734  0.0
31 -0.639994 -0.509547 -0.520776 -0.520776  0.0
32  0.875043  1.410588  1.403135  1.403135  0.0
33  3.578429  3.315956  3.312251  3.312251  0.0
34  0.066247  0.429955  0.428575  0.428575  0.0
35  4.452358  4.487255  4.484478  4.484478  0.0
36  1.811517  2.652440  2.650295  2.650295  0.0
37  1.265654  1.957320  1.955414  1.955414  0.0
38  1.700856  2.511520  2.509424  2.509424  0.0
39  1.113347  1.763368  1.761528  1.761528  0.0
40  4.280544  4.268462  4.265760  4.265760  0.0
41  4.954159  5.126265  5.123268  5.123268  0.0
42  4.026616  3.945101  3.942511  3.942511  0.0
43  2.024513  2.867409  2.862821  2.862821  0.0
44  3.498284  3.214382  3.210477  3.210477  0.0
45  2.106493  2.971308  2.966925  2.966925  0.0
46  3.666215  3.486154  3.483722  3.483722  0.0
47  1.614964  2.348353  2.342745  2.342745  0.0
48  4.276837  4.201108  4.199144  4.199144  0.0
49  5.022144  5.212840  5.209814  5.209814  0.0

### RR MSE

In [16]:
torch.sqrt(torch.mean( torch.mean( (RR2[:,:,:1] - RR2[:,:,1:]) ** 2,0),0))

tensor([68.1122,  1.4779,  0.5767,  2.3675])

### regresion MSE

In [17]:
torch.sqrt(torch.mean( torch.mean( (f2[:,:,:1] - f2[:,:,1:]) ** 2,0),0))

tensor([0.5036, 0.5012, 0.5012, 3.1795])